"""add fk note.user_id to user with cascade

Revision ID: b6123e3e301d
Revises: f51a723d01b3
Create Date: 2026-09-07 10:46:04.718591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6123e3e301d'
down_revision: Union[str, Sequence[str], None] = 'f51a723d01b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 제약 이름을 명시한다. None으로 두면 DB가 임의 이름을 붙여서 downgrade가 동작하지 않는다
    op.create_foreign_key(
        'fk_Note_user_id_User', 'Note', 'User', ['user_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Note_user_id_User', 'Note', type_='foreignkey')
    # ### end Alembic commands ###
